### ISSUE TITLE
Consider preparing venv and virtualenv sessions without setuptools and wheel

### ISSUE THREAD

**Issue by layday** [wntrblm/nox#557]
Provisioning test envs without setuptools and wheel can help catch undeclared dependencies on these two packages and will smoothen the eventual transition to a setuptool-less pip and ensurepip (and therefore venv), for packages which continue to rely on pip's legacy install mechanism or direct `setup.py` invocation.  This will cause breakage but the (interim) solution will be a simple `session.install("setuptools", "wheel")`.

**Comment by cjolowicz** [comment]
I agree that removing hidden dependencies on setuptools and wheel is the path forward for the ecosystem. But I'm not sure that Nox should be the one to force this. Nox does not install these packages into environments, virtualenv does. Users can already catch undeclared dependencies by exporting `VIRTUALENV_NO_SETUPTOOLS` and `VIRTUALENV_NO_WHEEL` when invoking Nox.

What's virtualenv's strategy here? cc @gaborbernat

Also yes, it will definitely cause breakage. For example, [pbr](https://bugs.launchpad.net/pbr/+bug/1868899) has an undeclared dependency on setuptools, and is widely used.

**Comment by cjolowicz** [comment]
FWIW virtualenv installs setuptools and wheel by default, `python -m venv` installs setuptools, not wheel.

```python
import nox

@nox.session(python="3.10")
def virtualenv(session):
    session.run("python", "-c", "import setuptools, wheel")

@nox.session(python="3.10", venv_backend="venv")
def venv(session):
    session.run("python", "-c", "import setuptools, wheel")  # ModuleNotFoundError: No module named 'wheel'
```

```console
❯ .nox/venv/bin/pip freeze --all
pip==21.2.4
setuptools==58.1.0

❯ .nox/virtualenv/bin/pip freeze --all
pip==21.3.1
setuptools==60.2.0
wheel==0.37.1
```

**Comment by gaborbernat** [comment]
IMHO this is a decision for nox/tox maintainers. I'd be +1 for it.

**Comment by cjolowicz** [comment]
I'm still worried about the fallout of this move.

Take pbr which has almost 50 dependents among the top 5000 PyPI packages, such as mock and bandit. This decision does not affect just the offending packages like pbr, or even their users, like bandit. It will affect any package that uses bandit for their checks (and their checks will break the moment bandit is imported, so every time).

Would it be feasible to check which top 5000 packages import setuptools without declaring it as a dependency, and approach the maintainers?

If we can get the most important offenders fixed, I'd be fine with Nox taking the first step here in changing the defaults, before virtualenv.

**Comment by FollowTheProcess** [comment]
I'd be cautious of this personally. I can't recall an exact working (or rather breaking) example right now but I've created several environments in the past where the lack of wheel or an outdated version of setuptools has caused installation problems.

Packages like Numpy and Pandas on macOS fall into this category most often where I've found the lack of wheel causing compilation from source and then subsequently failing because of missing system dependencies like blas/lapack.

I agree with @cjolowicz that eventually the ecosystem is going to have to drop reliance on these packages but I personally think we're a long way from that at the moment and if Nox were to be an early adopter of this approach and people's sessions start failing it doesn't reflect well on the project

**Comment by gaborbernat** [comment]
IMHO the early adopter here should be nox/tox because people using those are probably mildly advanced and care enough about best practices to fix it. I don't see who else are we expecting to make this change. Besides with pip the latest pip implementing PEP-660 there's no more case when pip would use the provisioned wheels/setuptools.

**Comment by FollowTheProcess** [comment]
> Besides with pip the latest pip implementing PEP-660 there's no more case when pip would use the provisioned wheels/setuptools.

Huh, cool! I wasn't aware of this, thanks!

**Comment by layday** [comment]
That was my thinking too, that an isolated testing environment is the best place to start, and that it might reduce the fallout, not for nox, but for pip when pip gets around to flicking that dreaded switch.  However, there's a real danger that instead of adopting a PEP 517-based workflow, nox users will take the easy way out by installing setuptools and wheel, and we'll have squandered a rare opportunity to help them switch.

> Besides with pip the latest pip implementing PEP-660 there's no more case when pip would use the provisioned wheels/setuptools.

pip still uses the legacy path for packages without a `pyproject.toml`. If wheel is installed it'll call `bdist_wheel` and install the wheel normally; if wheel is not installed (i.e. if you're in a stdlib venv) it'll call `setup.py install`.

**Comment by cjolowicz** [comment]
> the early adopter here should be nox/tox because people using those are probably mildly advanced and care enough about best practices to fix it.

The problem is that they can't actually fix it. They can only work around it, and report it upstream.

> pip still uses the legacy path for packages without a `pyproject.toml`. If wheel is installed it'll call `bdist_wheel` and install the wheel normally; if wheel is not installed (i.e. if you're in a stdlib venv) it'll call `setup.py install`.

So users will be broken if their dependency tree includes setup.py-only packages with only sdist available on PyPI? That seems like a  considerable problem in itself.

But my concerns above were unrelated to pip and build dependencies, they were about runtime dependencies. This may not have been clear from my earlier comment, so please let me elaborate.

Bandit has a runtime dependency on pbr (to compute its `__version__` attribute), and pbr has an *undeclared* runtime dependency on setuptools. The bug and its duplicates are almost two years old, with no response from the maintainer. Every single user of bandit (via Nox/tox) will be broken by this move, instantly. Their CI will fail with a cryptic traceback, entirely unrelated to their project, and hidden deep in their dependency tree. (By the way, this is not a theoretical scenario, it will affect every single user of my project template.)

And I have a feeling that this might be just the tip of the iceberg. Hence the idea to analyze the [top 5000](https://hugovk.github.io/top-pypi-packages) packages for setuptools imports, on a best-effort basis, maybe using Victor Stinner's scripts ([here](https://github.com/vstinner/misc/blob/main/cpython/download_pypi_top.py) and [here](https://github.com/vstinner/misc/blob/main/cpython/search_pypi_top.py)). The hard thing about this is figuring out whether the dependency tree includes setuptools. But I suppose in this case we could also just `pip install` and `pip freeze` for each of them? Libraries.io does not seem to have accurate information FWIW.)

**Comment by gaborbernat** [comment]
> The problem is that they can't actually fix it. They can only work around it, and report it upstream.

Do not populate by default. Allow some configuration flag that enables it. The small group who need it can enable the flag.

**Comment by cjolowicz** [comment]
See also https://github.com/python/cpython/issues/95299

**Comment by henryiii** [comment]
On python 3.12+, this is done automatically by venv/virtualenv. And the uv backend always does it.
