### ISSUE TITLE
Error messaging doesn't help me

### ISSUE THREAD

**Issue by barbaricyawps** [wntrblm/nox#599]
Hi. I upgraded to Ubuntu 22.04 today and for some reason, it's breaking my ability to use Nox inside my Python virtual environment.

I can't troubleshoot the problem because the error messaging and Nox documentation are incomplete and don't cover my scenario.

When I try to compile the docs using `nox -e docs` or any flavor of those commands. I get this output:

```
Running session docs
nox > Re-using existing virtual environment at .nox/docs.
nox > python -m pip install --progress-bar=off -U pip setuptools wheel
nox > Error: python is not installed into the virtualenv, it is located at /my-project-root-directory/.venv/bin/python. Pass external=True into run() to explicitly allow this.
nox > Session docs failed.
```

I have no idea what it means to pass external=True into run(). Can you add what that means to the documentation or explain it better in the error messaging? It's not clear to me what commands I run and when.

**Comment by barbaricyawps** [comment]
Update: Apparently, setting `nox.options.reuse_existing_virtualenvs = False` in the `noxfile.py` fixed the error.

**Comment by FollowTheProcess** [comment]
Hi @barbaricyawps, could you share your Noxfile?

From a quick glance it looks like you're invoking python manually from within a nox session e.g.:

```python
session.run("python", "-m", "pip", "install"...)
```

In most cases this is unnecessary. I only really use it when I'm trying to invoke the global project python for something (not the nox session's python)

That's why nox is saying "not found in the virtual environment" because you're actually invoking the global python here. This is handled here: https://github.com/wntrblm/nox/blob/f3adccbb8ab377638786b11cb754a04a9e613132/nox/command.py#L107-L111

If you do truly want to access the global python, you should pass `external=True` to `session.run` like this:

```python
session.run("python", "-m", "pip", "install"...., external=True)
```

However, this will install whatever you pass into the global or project's python, which is most likely **not** what you want!

More likely what you want to do is install using the nox session's python, in which case what you want to do is this:

```python
session.install("--progress-bar=off", "-U", "pip", "setuptools", "wheel")
```

Hope that helps!

**Comment by FollowTheProcess** [comment]
> Update: Apparently, setting `nox.options.reuse_existing_virtualenvs = False` in the `noxfile.py` fixed the error.

@barbaricyawps Can I take it you've resolved the problem? i.e. is this issue now no longer needed?

**Comment by barbaricyawps** [comment]
Yes, I resolved the issue. Closing.
